Fix missing `--region` flag for `lb_config` data `aws ecs describe-services ...` call
buildkite-plugins/ecs-deploy-buildkite-plugin pull request #102
Opened 2024-01-08 18:47 UTC by t1maccapp

When running buildkite agent in a different AWS Region to ECS cluster, the command fails with this message:
```
An error occurred (ClusterNotFoundException) when calling the DescribeServices operation: Cluster not found.
🚨 Error: The command exited with status 255
user command error: The plugin ecs-deploy command hook exited with status 255
```

I noticed that when calling awc cli for obtaining `lb_config` data `--region` flag is missing.

2024-01-08 19:16 UTC, t1maccapp commented
1. Test added `Run a deploy when region is specified`
2. I also noticed that for `aws ecs describe-services` both `--service` and `--services` option names are used. Changed it to use `--services` only as per [docs](https://docs.aws.amazon.com/cli/latest/reference/ecs/describe-services.html#options)<img width="700" alt="image" src="https://github.com/buildkite-plugins/ecs-deploy-buildkite-plugin/assets/8779881/88ca11e8-e9c0-45d1-a977-e2a1797c254e">

2024-01-10 10:27 UTC, t1maccapp commented
What I missed at first and now is fixed with latest commits:
1. The last `aws ecs describe-services` call was not using `aws_describe_service_args`
2. There are more tests in `existing-data.bats`, it is now updated too

2024-01-11 18:04 UTC, t1maccapp commented
Found one more call without taking `aws_default_args` into account, had to move a few things around to update it.

I still can't figure out how to run bats test locally, sorry. The initial intention was to fix one small thing with one-liner 🗿

2024-03-13 00:30 UTC, toote requested changes
@t1maccapp thanks for the contribution, the tests were failing due to a bash issue in your changes but it is a great change so, instead of asking you to fix it after 2 months, I have incorporated them all in a major overhaul of the code (see #106)

2024-03-13 00:30 UTC, toote commented on hooks/command
> +if ! existing_task_definition >"${task_file}"; then
this is what is causing the error as this would try executing an `existing_task_definition` command instead of sending the contents of the variable to the file like the command did

2024-03-22 16:53 UTC, closed without merging